// Aho-Corasick multi-pattern string matching.
//
// Free of any Python or nanobind dependency: bindings.cpp is the only file that
// knows Python exists. Being a module rather than a header enforces the other
// half of that - the node type, the transition function and the traversal are
// private in a way a header cannot express.
//
// The standard library is included in the global module fragment rather than
// imported: `import std;` needs a newer toolchain than this project asks for.
//
// AHOCORASICK_EXPORT is unrelated to `export` despite the name. `export` says
// what an importer may spell; the macro says what reaches the dynamic symbol
// table, which the build hides by default. It is applied per member so the ABI
// surface matches the language surface - annotating the class would export the
// private internals this module exists to hide.

module;

// Generated by CMake. Included here because macros do not cross a module
// boundary, so a command-line define would be invisible below.
#include <ahocorasick_export.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <functional>
#include <numeric>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

export module aho_corasick;

export namespace ac {

// Builds an automaton from a fixed pattern set, then finds every occurrence of
// every pattern in a single pass. Construction is the expensive part; scanning is
// O(text length) and independent of the pattern count. That asymmetry is why this
// type exists.
class PatternMatcher {
public:
    struct Match {
        std::size_t start;          // offset of the occurrence within the text
        std::size_t pattern_index;  // index into the pattern list

        bool operator==(const Match&) const = default;
    };

    struct Pattern {
        std::string text;
        std::size_t chars;  // length in code points; text.size() is the byte length
    };

    // Scanning tracks both units; the caller picks the one matching its input.
    // Byte offsets into UTF-8 text disagree with every offset Python reports.
    enum class Offsets { Bytes, Characters };

    // Throws std::invalid_argument if any pattern is empty; an empty pattern
    // matches at every position, which is never what a caller means.
    AHOCORASICK_EXPORT explicit PatternMatcher(std::span<const std::string> patterns);

    // True if any pattern occurs at least once. Stops at the first hit.
    [[nodiscard]] AHOCORASICK_EXPORT bool matches(std::string_view text) const noexcept;

    // Total occurrences of all patterns, counting overlaps.
    [[nodiscard]] AHOCORASICK_EXPORT std::size_t count(std::string_view text) const noexcept;

    // Every occurrence, in the order encountered. Overlapping and nested matches
    // are all reported: searching "he", "she", "hers" in "shers" yields all three.
    //
    // Offsets::Characters assumes valid UTF-8; on arbitrary bytes the character
    // positions are meaningless, but harmless, with no undefined behaviour.
    [[nodiscard]] AHOCORASICK_EXPORT std::vector<Match> find_all(std::string_view text,
                                                                 Offsets offsets) const;

    // Implicitly inline, but still annotated: a member of a named module is
    // emitted in the module's own translation unit, not duplicated into importers.
    [[nodiscard]] AHOCORASICK_EXPORT std::size_t num_patterns() const noexcept {
        return patterns_.size();
    }
    [[nodiscard]] AHOCORASICK_EXPORT std::size_t num_states() const noexcept {
        return nodes_.size();
    }
    [[nodiscard]] AHOCORASICK_EXPORT std::span<const Pattern> patterns() const noexcept {
        return patterns_;
    }

private:
    using Child = std::pair<std::uint8_t, std::int32_t>;  // (byte, next state)

    struct Node {
        // Sorted by byte, so the lookup below can stop early. A dense table
        // indexed by byte would be one load instead of a loop, but its per-state
        // cost dominates memory once there are many patterns, and it measured no
        // faster: the loop it replaces is already short.
        std::vector<Child> children;
        std::int32_t fail = 0;
        std::int32_t output_link = -1;       // nearest proper suffix that is terminal
        std::vector<std::int32_t> outputs;   // patterns ending exactly here
    };

    // States are int32_t indices, so every access would otherwise need a cast.
    [[nodiscard]] const Node& node(std::int32_t state) const noexcept {
        return nodes_[static_cast<std::size_t>(state)];
    }
    [[nodiscard]] Node& node(std::int32_t state) noexcept {
        return nodes_[static_cast<std::size_t>(state)];
    }

    // The innermost operation of every scan, and the only loop here hot enough to
    // justify writing against the idiomatic spelling twice over. Linear rather
    // than binary search, because child lists are short and a binary search
    // branches on data the predictor cannot learn. Written out rather than
    // ranges::find_if, which must find the first entry not below the byte and then
    // re-test it, where this returns the instant it matches.
    [[nodiscard]] std::int32_t child(std::int32_t state, std::uint8_t byte) const noexcept {
        for (const auto& [key, next] : node(state).children) {
            if (key == byte) {
                return next;
            }
            if (key > byte) {
                break;  // sorted, so no later entry can match
            }
        }
        return -1;
    }

    // Follow failure links until the byte can be consumed, or fall back to root.
    [[nodiscard]] std::int32_t step(std::int32_t state, std::uint8_t byte) const noexcept;

    void build_failure_links();

    // Single shared traversal. on_match returns false to stop early, which is how
    // `matches` avoids scanning the rest of the text.
    template <typename OnMatch>
    void scan(std::string_view text, OnMatch on_match) const;

    std::vector<Node> nodes_;
    std::vector<Pattern> patterns_;
};

}  // namespace ac

// Definitions live in aho_corasick.cpp. Only this file's declarations form the
// compiled interface, so editing a body there does not recompile importers.
//
// A private module fragment would keep both halves in one file, but GCC has not
// implemented it; an implementation unit is portable and does the same job.
