// Aho-Corasick multi-pattern string matching.
//
// A C++20 module, and deliberately free of any Python or nanobind dependency:
// this file compiles as a plain C++ library, and `bindings.cpp` is the only file
// that knows Python exists. That separation is the point of the layout, and the
// module boundary now enforces the other half of it. Only the names marked
// `export` are visible to an importer; the trie node type, the transition
// function and the traversal are private in a way a header cannot express.
//
// The standard library is included in the global module fragment rather than
// imported. `import std;` needs a newer toolchain than this project asks for,
// and mixing the two forms is worse than picking one.
//
// `export` above is a language-level notion: it says what an importer may name.
// It says nothing about the dynamic symbol table, which the build hides by
// default. In a shared build the two must be reconciled explicitly, which is
// what AHOCORASICK_EXPORT does below; in a static build the macro expands to
// nothing and the symbols stay hidden. It is applied per member rather than to
// the class as a whole, so that the ABI surface matches the language surface —
// annotating the class would export the private trie internals this module
// exists to hide.

module;

// Generated by CMake (GenerateExportHeader). It has to be included here in the
// global module fragment: macros do not cross a module boundary, so a definition
// supplied on the command line would be invisible below.
#include <ahocorasick_export.h>

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <functional>
#include <numeric>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

export module aho_corasick;

export namespace ac {

// Builds an automaton from a fixed pattern set, then finds every occurrence
// of every pattern in a text in a single pass.
//
// Construction is the expensive part and happens once; scanning is O(text
// length) and, crucially, independent of how many patterns were registered.
// That asymmetry is the whole reason this type exists.
class PatternMatcher {
public:
    struct Match {
        std::size_t start;          // offset of the occurrence within the text
        std::size_t pattern_index;  // index into the pattern list

        bool operator==(const Match&) const = default;
    };

    struct Pattern {
        std::string text;
        std::size_t chars;  // length in code points; text.size() is the byte length
    };

    // Text arriving from a Python `str` is UTF-8, where a byte offset is a
    // footgun: it disagrees with every offset Python itself would report.
    // Scanning tracks both, and the caller picks the unit that matches its input.
    enum class Offsets { Bytes, Characters };

    // Throws std::invalid_argument if any pattern is empty; an empty pattern
    // matches at every position, which is never what a caller means.
    AHOCORASICK_EXPORT explicit PatternMatcher(std::span<const std::string> patterns);

    // True if any pattern occurs at least once. Stops at the first hit.
    [[nodiscard]] AHOCORASICK_EXPORT bool matches(std::string_view text) const noexcept;

    // Total occurrences of all patterns, counting overlaps.
    [[nodiscard]] AHOCORASICK_EXPORT std::size_t count(std::string_view text) const noexcept;

    // Every occurrence, in the order encountered. Overlapping and nested matches
    // are all reported: searching "he", "she", "hers" in "shers" yields all three.
    //
    // Offsets::Characters assumes valid UTF-8; on arbitrary bytes the character
    // positions are meaningless, but harmless, with no undefined behaviour.
    [[nodiscard]] AHOCORASICK_EXPORT std::vector<Match> find_all(std::string_view text,
                                                                 Offsets offsets) const;

    // Defined in-class and so implicitly inline, but they still need annotating:
    // a member of a named module is emitted in the module's own translation unit,
    // not duplicated into each importer the way a header's inline would be.
    [[nodiscard]] AHOCORASICK_EXPORT std::size_t num_patterns() const noexcept {
        return patterns_.size();
    }
    [[nodiscard]] AHOCORASICK_EXPORT std::size_t num_states() const noexcept {
        return nodes_.size();
    }
    [[nodiscard]] AHOCORASICK_EXPORT std::span<const Pattern> patterns() const noexcept {
        return patterns_;
    }

private:
    using Child = std::pair<std::uint8_t, std::int32_t>;  // (byte, next state)

    struct Node {
        // Sorted by byte, so the lookup below can stop early. Kept as a small
        // vector rather than a dense table indexed by byte: dense would be one
        // load instead of a loop, but costs a kilobyte per state, which dominates
        // memory once there are many patterns. It was also no faster in practice,
        // because the lookup it replaces is already short.
        std::vector<Child> children;
        std::int32_t fail = 0;
        std::int32_t output_link = -1;       // nearest proper suffix that is terminal
        std::vector<std::int32_t> outputs;   // patterns ending exactly here
    };

    // States are held as int32_t indices, so every access would otherwise need a
    // static_cast. One named accessor is worth fifteen casts inline.
    [[nodiscard]] const Node& node(std::int32_t state) const noexcept {
        return nodes_[static_cast<std::size_t>(state)];
    }
    [[nodiscard]] Node& node(std::int32_t state) noexcept {
        return nodes_[static_cast<std::size_t>(state)];
    }

    // The innermost operation of every scan. Two deliberate choices, both against
    // the more idiomatic spelling:
    //
    //   - A linear scan, not a binary search. Child lists are short, and a binary
    //     search branches on data the predictor cannot learn, so it mispredicts
    //     roughly every other lookup.
    //   - Written out, not std::ranges::find_if. find_if must locate the first
    //     entry not below the byte and then re-test it for equality, where this
    //     returns the instant it matches.
    //
    // Everything else in this file uses the ranges algorithms. This is the only
    // loop hot enough to be worth hand-writing.
    [[nodiscard]] std::int32_t child(std::int32_t state, std::uint8_t byte) const noexcept {
        for (const auto& [key, next] : node(state).children) {
            if (key == byte) {
                return next;
            }
            if (key > byte) {
                break;  // sorted, so no later entry can match
            }
        }
        return -1;
    }

    // The automaton's transition function: follow failure links until the byte
    // can be consumed, or fall back to the root.
    [[nodiscard]] std::int32_t step(std::int32_t state, std::uint8_t byte) const noexcept;

    void build_failure_links();

    // Single shared traversal. `on_match(pattern_index, byte_end, char_end)`
    // returns false to stop early, which is how `matches` avoids scanning the
    // rest of the text.
    template <typename OnMatch>
    void scan(std::string_view text, OnMatch on_match) const;

    std::vector<Node> nodes_;
    std::vector<Pattern> patterns_;
};

}  // namespace ac

// The definitions live in a module implementation unit (aho_corasick.cpp), not
// here. That is what keeps a change to a function body from recompiling every
// importer: only this file's exported declarations form the compiled interface.
//
// The obvious spelling for that is a private module fragment, `module :private;`,
// which would keep both halves in one file. GCC has not implemented it, so the
// separation is done with an implementation unit instead, which is portable and
// achieves the same thing.
